### ISSUE TITLE
UserExistsError when register

### ISSUE THREAD

**Issue by yifan** [saintedlama/passport-local-mongoose#198]
I am getting UserExistsError when registering new user. It does create a new user in database though.
Here is my model:
```
var User = new Schema({
  email: String,
  password: String
});

User.plugin(passportLocalMongoose, { usernameField: 'email' });
```
the log is here:
```
2017-02-15T06:07:27.851508+00:00 app[web.1]: error while user register! { AuthenticationError
2017-02-15T06:07:27.851510+00:00 app[web.1]:     at /app/node_modules/passport-local-mongoose/index.js:244:19
2017-02-15T06:07:27.851511+00:00 app[web.1]:     at /app/node_modules/mongoose/lib/query.js:2546:18
2017-02-15T06:07:27.851512+00:00 app[web.1]:     at newTickHandler (/app/node_modules/mpromise/lib/promise.js:234:18)
2017-02-15T06:07:27.851513+00:00 app[web.1]:     at _combinedTickCallback (internal/process/next_tick.js:67:7)
2017-02-15T06:07:27.851514+00:00 app[web.1]:     at process._tickCallback (internal/process/next_tick.js:98:9)
2017-02-15T06:07:27.851515+00:00 app[web.1]:   name: 'UserExistsError',
2017-02-15T06:07:27.851516+00:00 app[web.1]:   message: 'A user with the given username is already registered' }
2017-02-15T06:07:27.859168+00:00 app[web.1]: AuthenticationError
2017-02-15T06:07:27.859171+00:00 app[web.1]:     at /app/node_modules/passport-local-mongoose/index.js:244:19
2017-02-15T06:07:27.859172+00:00 app[web.1]:     at /app/node_modules/mongoose/lib/query.js:2546:18
2017-02-15T06:07:27.859173+00:00 app[web.1]:     at newTickHandler (/app/node_modules/mpromise/lib/promise.js:234:18)
2017-02-15T06:07:27.859173+00:00 app[web.1]:     at _combinedTickCallback (internal/process/next_tick.js:67:7)
2017-02-15T06:07:27.859174+00:00 app[web.1]:     at process._tickCallback (internal/process/next_tick.js:98:9)
```

I double checked, there is only one post to register url, and the user is indeed new user. I am suspecting it has something to do with the fact I am not using the default user field maybe?

**Comment by yifan** [comment]
It is actually wrong logic on my side. I was trying to do register and automatically log in user after it. Somehow it is trying to register again.
