### ISSUE TITLE
Cast to Number failed for value "NaN" at path "attempts"

### ISSUE THREAD

**Issue by espindl** [saintedlama/passport-local-mongoose#219]
My schema uses plugin like this:

```
....
var passportLocalMongoose = require('passport-local-mongoose');
....
accountSchema.plugin(passportLocalMongoose, { selectFields : 'username email', limitAttempts: true, maxAttempts:3});
```

When login fails I get a cast error: **Cast to Number failed for value "NaN" at path "attempts"**

But in mongodb I see the attempts field as "0".

**Comment by saintedlama** [comment]
Could you provide a test or a stack trace of the exception?

**Comment by carlgrimm** [comment]
Same here, recently upgraded and this is happening now on my users on a login fail.

ValidationError: User validation failed: loginAttempts: Cast to Number failed for value "NaN" at path "loginAttempts"
    at ValidationError.inspect (/mnt/c/Users/cg/Source/Repos/Backend/node_modules/mongoose/lib/error/validation.js:56:24)
    at formatValue (util.js:430:38)
    at inspect (util.js:324:10)
    at format (util.js:191:12)
    at Console.log (console.js:130:21)
    at passport.authenticate (/mnt/c/Users/cg/Source/Repos/Backend/server.js:260:15)
    at Strategy.strategy.error (/mnt/c/Users/cg/Source/Repos/Backend/node_modules/passport/lib/middleware/authenticate.js:353:18)
    at verified (/mnt/c/Users/cg/Source/Repos/Backend/node_modules/passport-local/lib/strategy.js:81:28)
    at promise.then.catch.err (/mnt/c/Users/cg/Source/Repos/Backend/node_modules/passport-local-mongoose/index.js

**Comment by jotade** [comment]
when using selectFields option, and 'attempts' field is not included, the query returns undefined, because the it cant find the the attempts field on the user object
