### ISSUE TITLE
 Error: Cannot find module '../build/Release/bson

### ISSUE THREAD

**Issue by ValmirJuniorr** [saintedlama/passport-local-mongoose#220]
Sou iniciante em NodeJS Fiz o clone do projeto então executei o npm install e então apareceu esse erro.

{ Error: Cannot find module '../build/Release/bson'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/junior/development/projects/nodeJS/passport-local-mongoose/examples/login/node_modules/bson/ext/index.js:15:10)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3) code: 'MODULE_NOT_FOUND' }
js-bson: Failed to load c++ bson extension, using pure JS version

**Comment by saintedlama** [comment]
If you just want to use passport-local-mongoose there is no need to clone but to `npm install passport-local-mongoose`. The issue arises if the bson native module could not be compiled/installed. Please make sure you have all the required build dependencies installed. If you're on windows you can try https://www.npmjs.com/package/windows-build-tools

**Comment by ValmirJuniorr** [comment]
OK thanks, man i'm usning linux, but i've stopped the devlopment in this project wohever i'll try it.
